### ISSUE TITLE
Devdiaries

### ISSUE THREAD

**Issue by martistuwe** [AHeinisch/Full-Stack#14]
Ordner wurde umbenannt ohne die Verlinkungen in _sidebar.md anzupassen. Ordnername enthält außerdem noch immer Schreibfehler.

**Comment by AHeinisch** [comment]
Wird behoben sobald @kroeker97 meinen Typo behoben hat (damit er keine harten merge konflikt bekommt. Vielen dank @martistuwe das dir es aufgefallen ist.

**Comment by AHeinisch** [comment]
ist jetzt behoben und das umbenennen des Ordners wurde auch gemacht
