### ISSUE TITLE
contributing.md umbenennen

### ISSUE THREAD

**Issue by reinkepatrick** [AHeinisch/Full-Stack#16]
Wie wäre es wenn die `contributing.md` zur `README.md` wird, so wird sie nicht so schnell übersehen.

**Comment by AHeinisch** [comment]
Ich glaube verlinken in der README.md sollte ausreichen oder spricht da was gegen?

 freue mich das du Feedback einbringst

**Comment by reinkepatrick** [comment]
Könnte man machen, aber was soll denn in die `README.md` rein, weil wenn da nichts reinkommt könnte man es ja als `README.md` nehmen.

**Comment by kroeker97** [comment]
Ich finde in der README sollte ein unterpunkt contributing sein. Wenn man nur eine contributing.md wird die übersehen.

**Comment by AHeinisch** [comment]
Ich habe den Text nun auch in der Readme somit wird es sowohl auf github direkt angezeigt sowie in unserer Doku .
