### ISSUE TITLE
Neues Thema zur Sidebar hinzufügen "Netzwerkprotokolle"

### ISSUE THREAD

**Issue by AMatutat** [AHeinisch/Full-Stack#41]

**Comment by AHeinisch** [comment]
was genau wird nicht angezeigt ? ihr habt doch eure Index da könnt ihr alles reinschreiben was ihr wollt ?

**Comment by reinkepatrick** [comment]
Ich glaube er meint das er ein neuen Ordner `Netzwerkprotokolle` hat und das dieser zur `_sidebar.md` hinzugefügt werden soll.

**Comment by AHeinisch** [comment]
Wurde behoben und eingefügt. Beschreibung wäre gut gewesen
