### ISSUE TITLE
Format für devdiary

### ISSUE THREAD

**Issue by AHeinisch** [AHeinisch/Full-Stack#9]
Im Sinne das alle Tagebücher ähnlich aussehen würde ich vorschlagen wir passen unsere Tagebücher an das von Patrick Reinke.

In dem Tagebuch soll die ungefähre Dauer eingetragen werden. Außerdem in kleinen blöcken 10 Minuten bis 2 Stunden.

**Comment by abergy** [comment]
Hab ich geändert, kann allerdings grade nicht pushen.
